config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trade.urls', namespace='trade')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trade/urls.py
from trade.apps import TradeConfig
from django.urls import path

from trade.views import ItemDetailView, ItemListView, get_payment_session, create_pre_order, pre_order_detail, \
    get_success_page

app_name = TradeConfig.name

urlpatterns = [
    path('', ItemListView.as_view(), name='trade_list'),
    path('item/<int:pk>/', ItemDetailView.as_view(), name='trade_detail'),
    path('mark_for_trade/<int:pk>/', create_pre_order, name='mark_for_trade'),  # Метод для пометки товара для покупки

    path('buy/', get_payment_session, name='create_payment_session'),
    path('pre_order/', pre_order_detail, name='pre_order_detail'),
    path('created_order/', get_success_page, name='create_success_page'),  # Создание заказа
]

trade/models.py
import uuid

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.


NULLABLE = dict(blank=True, null=True)


class Currency(models.Model):
    """Модель курса валют"""
    code = models.CharField(max_length=3, verbose_name='буквенный код', help_text='введите 3х-значный буквенный код')
    name = models.CharField(max_length=150, verbose_name='полное название курса', help_text='')
    related_currency = models.CharField(max_length=3, help_text='введите 3х-значный буквенный код',
                                         verbose_name='отношение текущего курса к другому', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='страна валюты', help_text='ведите страну валюты')
    value = models.FloatField(verbose_name='курс валюты')

    def __str__(self):
        return f'{self.code}'.lower()

    class Meta:
        verbose_name = 'курс валюты'
        verbose_name_plural = 'курсы валют'
        ordering = ['pk', ]


class Tax(models.Model):
    """Модель налогов"""
    name = models.CharField(max_length=150, verbose_name='налог', help_text='введите наименование налога')
    tax_base = models.PositiveIntegerField(verbose_name='ставка', help_text='введите ставку налога в процентах')
    stripe_tax_id = models.CharField(max_length=200, verbose_name='id номер от stripe tax rate')

    def __str__(self):
        return f'{self.name} - {self.tax_base}'

    class Meta:
        verbose_name = 'налог'
        verbose_name_plural = 'налоги'


class Item(models.Model):
    """Модель наименования товара"""
    name = models.CharField(max_length=250, verbose_name='наименование', help_text='введите наименование')
    description = models.TextField(verbose_name='описание', help_text='ведите описание', **NULLABLE)
    price = models.FloatField(verbose_name='цена без налога', help_text='введите цену без налога')
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, verbose_name='валюта', help_text='введите валюту',
                                 **NULLABLE)
    tax = models.ForeignKey(Tax, on_delete=models.CASCADE, verbose_name='примененный налог к учету', **NULLABLE)
    is_for_preorder = models.BooleanField(default=False, verbose_name='признак покупки',
                                             help_text='положить в корзину?')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ['name', ]


class Discount(models.Model):
    """Модель скидок"""
    name = models.CharField(max_length=150, verbose_name='скидка', help_text='введите наименование скидки')
    discount_base = models.PositiveIntegerField(verbose_name='скидка', help_text='введите % скидки')

    def __str__(self):
        return f'{self.name} - {self.discount_base}'

    class Meta:
        verbose_name = 'скидка'
        verbose_name_plural = 'скидка'


class PreOrder(models.Model):
    """Модель корзины(предзаказ). После утверждения, модель стирается.
    Используется как промежуточная таблица.
    Можно было бы привязать к юзеру, но в нашем случае регистрация и модели юзера не предусмотрено"""
    # session_tag = models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный идентификатор сессии')
    client_ip = models.GenericIPAddressField(verbose_name='IP-адрес клиента', **NULLABLE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='товар')
    quantity = models.PositiveIntegerField(default=1, verbose_name='количество', validators=[MinValueValidator(1),
                                                                                             MaxValueValidator(10)])
    currency_pay = models.ForeignKey(Currency, on_delete=models.CASCADE, verbose_name='валюта расчета',
                                     help_text='введите валюту расчета', **NULLABLE)
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE, verbose_name='примененная скидка к заказу', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата обновления')


    class Meta:
        verbose_name = 'корзина'
        verbose_name_plural = 'корзины'

    def __str__(self):
        return f"Предзаказ для клиента {self.client_ip} ({self.item.name})"

class Order(models.Model):
    """Модель заказа"""
    order_number = models.CharField(max_length=50, verbose_name='номер заказа')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='товар')
    quantity = models.PositiveIntegerField(verbose_name='количество')
    tax = models.ForeignKey(Tax, on_delete=models.CASCADE, verbose_name='налог')
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE, verbose_name='скидка', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата обновления')

    def __str__(self):
        return f"Заказ #{self.order_number})"

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

trade/views.py
import logging

from django.http import HttpResponse, HttpResponseRedirect

from django.forms import modelformset_factory
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django import forms
from django.views.generic import DetailView, ListView, CreateView
from ipware import get_client_ip

from config.settings import STRIPE_SECRET_KEY
from trade.models import Item, Order, PreOrder, Currency, Tax
import stripe

from trade.services import generate_order_number


logger = logging.getLogger(__name__)
# Create your views here.


class ItemListView(ListView):
    """Класс списка товара"""
    model = Item


class ItemDetailView(DetailView):
    """Класс детализации товара"""
    model = Item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tax = get_object_or_404(Tax, name='НДС')
        context['tax'] = tax if tax else 0
        return context


def create_pre_order(request, pk):
    """Метод для пометки товара для покупки. Создание корзины(предзаказ).
    """
    quantity = request.GET.get('quantity', 1)
    obj = get_object_or_404(Item, pk=pk)
    client_ip, _ = get_client_ip(request)  # IP address
    preorder_by_ip = PreOrder.objects.filter(client_ip=client_ip)
    if not preorder_by_ip.exists():
        PreOrder.objects.create(item=obj, quantity=quantity, client_ip=client_ip)
        obj.is_for_preorder = True
        obj.quantity = quantity

    elif preorder_by_ip.exists() and obj in [_.item for _ in preorder_by_ip]:
        obj.is_for_preorder = False
        preorder_by_ip.delete()

    elif preorder_by_ip.exists() and not obj in [_.item for _ in preorder_by_ip]:
        obj.is_for_preorder = True
        PreOrder.objects.create(item=obj, quantity=quantity, client_ip=client_ip)
    obj.save()
    return redirect(reverse('trade:trade_detail', kwargs={'pk': obj.pk}))


def pre_order_detail(request):
    """Редактирование корзины. Добавил формсеты, чтобы была возможность удаления продукта из корзины, восстановления
    статуса False для is_for_preorder"""
    pre_order_formset = modelformset_factory(PreOrder, fields=['quantity'], extra=0, can_delete=True,
                                             widgets={'quantity': forms.NumberInput(attrs={'min': 1, 'max': 10}, )
                                                      })
    currencies = Currency.objects.all()
    total_sum = 0
    if request.method == 'POST':
        formset = pre_order_formset(request.POST, queryset=PreOrder.objects.all())
        if formset.is_valid():
            instances = formset.save(commit=False)  # без commit=False не будет работать удаление
            # Блок проверки удаленных объектов
            for deleted_obj in formset.deleted_objects:
                item = deleted_obj.item
                if not PreOrder.objects.filter(item=item).exclude(pk=deleted_obj.pk).exists():
                    item.is_for_preorder = False
                    item.save()
                deleted_obj.delete()
            # Сохранение изменений в БД
            for instance in instances:
                instance.save()

            # Блок расчета итоговой суммы в указанной валюте
            currency = get_object_or_404(Currency, id=request.POST.get('currency'))
            for pre_order in formset.queryset:
                pre_order.currency_pay = currency  # сохраняем выбранный курс валюты расчета в БД
                pre_order.save()
                if pre_order.item.currency == currency:
                    total_sum += (pre_order.item.price + (pre_order.item.price *
                                  get_object_or_404(Tax, name='НДС').tax_base / 100)) * pre_order.quantity
                else:
                    total_sum += (pre_order.item.price + (pre_order.item.price *
                        get_object_or_404(Tax, name='НДС').tax_base / 100)) * pre_order.quantity / get_object_or_404(
                        Currency, related_currency=currency.code).value

    else:
        formset = pre_order_formset(queryset=PreOrder.objects.all())

    return render(request, template_name='trade/preorder_detail.html', context={'formset': formset,
                                                                                'currencies': currencies,
                                                                                'total_sum': total_sum,
                                                                                'tax': get_object_or_404(Tax,
                                                                                                         name='НДС')})


def get_payment_session(request):
    """Метод для получения сессии оплаты. API Stripe не выдерживает суммы в рублях более 1 мрн р."""
    client_ip = get_client_ip(request)
    obj = PreOrder.objects.filter(client_ip=client_ip[0])
    stripe.api_key = STRIPE_SECRET_KEY
    if not obj:
        logger.warning("Корзина пуста для IP: %s", client_ip)
        return HttpResponseRedirect(reverse('trade:pre_order_detail'))

    line_items = []
    total_amount = 0  # Общая сумма платежа в копейках
    for pre_order in obj:
        try:
            if pre_order.currency_pay == pre_order.item.currency:
                price = int(pre_order.item.price * 100)  # умножается на 100 из-за копеек
            else:
                price = int(pre_order.item.price / pre_order.item.currency.value * 100)

            total_amount += price * pre_order.quantity
            line_items.append({
                'price_data': {
                    'currency': pre_order.currency_pay.code.lower(),
                    'product_data': {
                        'name': pre_order.item.name,
                    },
                    'unit_amount': price,
                    'tax_behavior': 'exclusive',
                },
                'quantity': pre_order.quantity,
                'tax_rates': [pre_order.item.tax.stripe_tax_id, ]
            })
        except AttributeError as e:
            logger.error("Ошибка атрибута для предзаказа: %s", e)
            return HttpResponseRedirect(reverse('trade:pre_order_detail'))

    if total_amount > 99999999:  # 999,999.99 рублей в копейках
        logger.error("Сумма платежа превышает допустимый лимит: %s копеек", total_amount)
        return HttpResponse("Сумма платежа превышает допустимый лимит в 999,999.99 рублей", status=400)

    try:
        session = stripe.checkout.Session.create(
        line_items=line_items,
        mode='payment',
        currency=obj[0].currency_pay,
        payment_method_types=['card'],
        success_url=f'{request.build_absolute_uri(reverse("trade:create_success_page"))}',
        cancel_url=f'{request.build_absolute_uri(reverse("trade:pre_order_detail"))}',
    )
    except stripe.InvalidRequestError as e:
        logger.error("Ошибка Stripe: %s", e)
        return HttpResponse("Недопустимая сумма или ошибка Stripe", status=400)

    return HttpResponseRedirect(session.url)
    


def get_success_page(request):
    client_ip = get_client_ip(request)
    obj = PreOrder.objects.filter(client_ip=client_ip[0])
    order_number = generate_order_number()
    if obj:
        for pre_order in obj:
            Order.objects.create(order_number=order_number, item=pre_order.item, quantity=pre_order.quantity,
                                 tax=pre_order.item.tax, discount=pre_order.discount)
            pre_order.item.is_for_preorder = False
            pre_order.item.save()  # Восстанавливаем доступный статус для корзины обратно
            pre_order.delete()  # Удаляем созданные предзаказы

    return render(request, 'trade/success_page.html',
           {'order_number': Order.objects.filter(order_number=order_number)})

trade/templates/trade/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Dmitry Krasheninnikov">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Pricing example · Bootstrap v5.3</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/pricing/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->

</head>
<body>


<div class="container py-3">
    {% include 'trade/includes/header.html' %}

    {% block content %}

    {% endblock %}

    {% include 'trade/includes/footer.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</div>
</body>
</html>

trade/templates/trade/item_detail.html
{% extends 'trade/base.html' %}
{% load math_filters %}

{% block content %}
<a href="{% url 'trade:trade_list' %}" class="btn btn-sm btn-primary" style="align-center">Назад к списку</a>

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center justify-content-center">
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">
                        {{ object.price|multiply:tax.tax_base }} {{ object.currency }}
                    </h1>
                    <div class="card-description">
                        {{ object.description }}
                    </div>

                    {% if not object.is_for_preorder%}

                    <form method="GET"  action="{% url 'trade:mark_for_trade' object.pk %}">
                        <input type="number" name="quantity" min="1" max="10" value="1" required>
                        <button type="submit" class="w-100 btn btn-sm btn-primary">В корзину</button>
                    </form>
                    {% else %}
                    <a href="{% url 'trade:mark_for_trade' object.pk %}" class="w-100 btn btn-sm btn-danger"
                       style="align-center">Убрать из корзины</a>
                    {% endif %}


                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

trade/templates/trade/item_list.html
{% extends 'trade/base.html' %}


{% block content %}


<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center justify-content-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <a href="{% url 'trade:trade_detail' object.pk %}" class="w-100 btn btn-lg btn-primary" style="align-center">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>

{% endblock %}

trade/templates/trade/preorder_detail.html
{% extends 'trade/base.html' %}
{% load math_filters %}
{% block content %}
<form method="POST">
    {% csrf_token %}

    <div class="currency-selector mb-4">
        <label class="form-label">Валюта расчета:</label>
        <select name="currency" class="form-select">
            {% for currency in currencies %}
                <option value="{{ currency.id }}"
                    {% if current_currency and currency.id == current_currency.id %}selected{% endif %}>
                    {{ currency.symbol }} ({{ currency.code }})
                </option>
            {% endfor %}
        </select>
    </div>

    {{ formset.management_form }}

    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>Товар</th>
                <th>Количество</th>
                <th>Цена за шт.</th>
                <th>Итого цена</th>
                <th>Валюта</th>
                <th>Удалить</th>
            </tr>
        </thead>
        <tbody>
            {% for form in formset %}
                {% if not form.DELETE.value %}  <!-- Скрываем помеченные на удаление -->
                <tr>
                    <td>
                        {{ form.id }}
                        {{ form.instance.item.name }}
                    </td>
                    <td>{{ form.quantity }}</td>
                    <td>{{ form.instance.item.price|multiply:tax.tax_base }}</td>
                    <td>{% total_item_amount form.instance.item.price tax.tax_base form.instance.quantity %}</td>
                    <td>{{ form.instance.item.currency }}</td>
                    <td>
                        <div class="form-check">
                            {{ form.DELETE }}
                        </div>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <div class="total-sum mb-3">
        <h4>Итого: {{ total_sum }} {{ current_currency.symbol }}</h4>
    </div>

    <button type="submit" class="btn btn-success">Сохранить изменения</button>
    <a href="{% url 'trade:create_payment_session' %}" class="btn btn-secondary">Оплатить</a>
    <br></br>
    <h6>Нажмите сохранить изменения для подсчета стоимости в указанной валюте</h6>
    <h6>При нажатии кнопки отправить, перенаправляетесь для оплаты с указанной валютой</h6>
</form>
{% endblock %}

trade/templates/trade/success_page.html
{% extends 'trade/base.html' %}
{% load math_filters %}
{% block content %}

{{ order_number}}

{% endblock %}